### ISSUE TITLE
Wenfangfan Task-1

### ISSUE THREAD

**Issue by MontyPan** [DontCareAbout/FlowTraining#2]
task 內容請參閱這份文件：https://github.com/DontCareAbout/FlowTraining/blob/master/Task_1.md

git、GitHub、Markdown 的教程，網路上免費資源很多，即使中文也有很完整的，請自己找喜歡的來看。
標準操作以外的部份則是寫在[《工作流程與作業規範》](https://github.com/DontCareAbout/FlowTraining/blob/master/README.md) 當中。

有問題可以直接在 issue 底下留 comment、或是發 mail 問，但是我通常都不會直接給你答案 :dancer: 

Enjoy it and have fun...... （謎之聲：會有 fun 才有鬼）

**Comment by Wenfangfan** [comment]
這裡嗎?

**Comment by Wenfangfan** [comment]
https://gist.github.com/Wenfangfan/a888a494639d2b6eff116233fbcfd088
目前只做好了markdown

**Comment by MontyPan** [comment]
> # 注意： #
> 請不要直接回 GitHub 的 notify email...... Orz
> 要寫 comment 請直接在 GitHub 的介面上寫
>尤其是沒有引言習慣，看的實在很累人... [下略數百字]

@Wenfangfan ：我不用知道你在完成 task 之前做了哪些事情，拜託你不要一直報告這種事情。

@blacklittle ：現在開同學會還太早了點... :see_no_evil:

**Comment by MontyPan** [comment]
距離上一次的 response 已經過了一陣子了（9 天），雖然沒有要催進度，但還是要問一下：還有在進行嗎？

**Comment by MontyPan** [comment]
多次沒有任何回應，所以掰掰... :see_no_evil:
