### ISSUE TITLE
weiting Task-2

### ISSUE THREAD

**Issue by MontyPan** [DontCareAbout/FlowTraining#35]
task 內容請參閱這份文件：https://github.com/DontCareAbout/FlowTraining/blob/master/Task_2.md

如果不打算回答 option question，請在發 PR 的 comment 告訴我。

**Comment by weiting9199** [comment]
Task_2.md 中的第 4 點有提到

> 修正被亂改 Task-1.md（會放在以你 GitHub 帳號名稱命名的目錄下），
> 並在檔案開頭加上 Task-1 的分數、以及被亂改的修正清單


沒有看到被亂改的修正清單

**Comment by MontyPan** [comment]
＝＝" 那是你要找出來給我的東西

**Comment by weiting9199** [comment]
可是 Don'tCareAbout/FlowTraining/weiting9199 裡面只有一個 Task-1.md
沒有被亂改，跟原本的長一樣

**Comment by weiting9199** [comment]
在 Don'tCareAbout/FlowTraining/weiting9199 目錄中的 Task-1.md
只有第二行增加了兩個「=」（因為字型問題原本沒發現沒有對齊）
如果改回原本的話就是要把兩個「=」刪除，這樣就不符合 Coding Style 了
其他部分都跟我原本的 Task-1.md 一樣。

**Comment by MontyPan** [comment]
* 「改回 task-1 結束時的樣子」這部份只會要求「得跟 task-1 一樣」，不會講究 coding style
* 哪來「Don'tCareAbout/FlowTraining」這個 repo？你找給我看
* 請不要再莫名其妙把首字字母變成大寫了
* 我在 Task-1 就告訴你要去弄個字型解決 header 對齊這件事情了... 你的原本到底是哪個平行宇宙的「原本」？

最後，你一開始的 comment 還信誓旦旦的說「沒有被亂改，跟原本的長一樣」（這時我才知道原來 comment 刪掉不會有紀錄.... Orz），然後現存的這個 comment 說找到了一個被亂改的地方....... 你真的對自己很有信心？那你就這樣交作業阿.... :smiling_imp: 

![](https://4.bp.blogspot.com/-Irl4aVQWzXk/XEbH9XsbfwI/AAAAAAAAQn0/IhDW_rzC4kktzb-QeUFAdgYXlVGustbKgCLcBGAs/s400/1.jpg)

好啦，我應該是變不出九種辦法啦，但隨便也有三四種辦法可以解決這件事情。而你會有這種困擾就表示

* 你的肉眼實在是很不行... 我覺得有九成原因是你不願意耐著性子作腳踏實地地作這種苦差事
    * 就是不想幹這種無腦苦差事所以才當程式設計師（對，我當程式設計師就是這原因），那寫個程式來比對不就得了（謎之聲：會寫我還來找你學寫程式）
* 你的 task-1 沒有確實吸收，或是你的回答是抄來的

最後補個大絕招，除非你有辦法 hack 掉我的帳號，不然我敢跟你賭「我真的改了一堆東西」，賭注要下多大都行。

你敢賭嗎？ :dancer:
