### ISSUE TITLE
Paul Task-1

### ISSUE THREAD

**Issue by MontyPan** [DontCareAbout/FlowTraining#61]
task 內容請參閱這份文件：https://github.com/DontCareAbout/FlowTraining/blob/master/Task_1.md

git、GitHub、Markdown 的教程，網路上免費資源很多，即使中文也有很完整的，請自己找喜歡的來看。
標準操作以外的部份則是寫在[《工作流程與作業規範》](https://github.com/DontCareAbout/FlowTraining/blob/master/README.md) 當中。

有問題可以直接在 issue 底下留 comment、或是發 mail 問，但是我通常都不會直接給你答案 :dancer: 

Enjoy it and have fun...... （謎之聲：會有 fun 才有鬼）

**Comment by m42532461** [comment]
請問 Task1 內的 GitHub 部分是要使用 git client 來操作嗎

**Comment by MontyPan** [comment]
我很確定 Task-1 的文件內容可以回答你問的問題

**Comment by m42532461** [comment]
![image](https://user-images.githubusercontent.com/88074031/129564989-873cc742-56f4-42bc-aeff-e1293f4222e4.png)
請問為何無法新增Task-1.md的檔案

**Comment by MontyPan** [comment]
* 如果你要問問題，請試著使用不用擷圖的方式
    * 就算你真的非捷圖不可，也不是整個螢幕擷圖下來給我。
        我沒有興趣也沒有義務要接受其他雜訊。
* 這個問題我不會回答
* 也可以這麼說：如果你連這個問題都需要問人，那很抱歉，我無法提供教學
* 當然，你的確有可能撞到無法解釋的靈異現象，但是從你的問題內容（哪怕你已經擷圖了... 😴 ）無從判斷起，那我也沒有責任要回答。

以上

**Comment by m42532461** [comment]
想請教關於 reject 的理由

1. 不符合 Task-1 的要求，而且無法透過後續修正補救
想請問詳細是哪個部分，是內容不符合，抑或是操作上哪個步驟有問題?
2. 每個 commit 要有意義且小步前進
如果是創造後，第一次編輯完就不再有版本更新，這樣算小步前進嗎?

**Comment by MontyPan** [comment]
1. 該告訴你的都已經告訴你了，我沒有義務也沒有責任要幫你畫重點。
    如果換個方式講你會比較開心的話：「我每一句話（ㄜ... 哏圖不算 XD）都是重點」
2. 關於第二點
    + **跟 reject 理由沒關係**，我在 PR 的 comment 已經寫的很清楚了。
        如果你不是那個意思，那就不應該寫成「第二點」
    + 前面的「如果」跟後面的「這樣」沒有必然的前後關係。
        一個類比沒那麼全面、但是好理解的例子：考試也可以寫了名字之後就交白卷。
    + 是的，「小步前進」不是一個可以明確定義的規範，存在主觀判定的部份
        所以在 #63 當中，你真的堅持要把第三、第四個 commit 拆開來做，
        （現階段）我也無法認真地控訴些什麼。反之，我挑出來的那三個 commit 則否。

不算題外話的順帶一提，那三點的先後順序是有意義、是特別寫成那樣子的。
如果每個 commit 沒有意義，那第三點的「小步前進」也就形同虛設。

同理，整個 FlowTraining 的設計也是有其意義、是特別寫成那個樣子的
（而且是出自於訓練目的而不是個人的惡趣味 💃 ）。
基於公平原則，我不能再講更多了。

**Comment by MontyPan** [comment]
deadline 已過，結案
