### ISSUE TITLE
wwl Task-1

### ISSUE THREAD

**Issue by MontyPan** [DontCareAbout/FlowTraining#73]
task 內容請參閱這份文件：https://github.com/DontCareAbout/FlowTraining/blob/master/Task_1.md

git、GitHub、Markdown 的教程，網路上免費資源很多，即使中文也有很完整的，請自己找喜歡的來看。
標準操作以外的部份則是寫在[《工作流程與作業規範》](https://github.com/DontCareAbout/FlowTraining/blob/master/README.md) 當中。

有問題可以直接在 issue 底下留 comment、或是發 mail 問，但是我通常都不會直接給你答案 :dancer: 

Enjoy it and have fun...... （謎之聲：會有 fun 才有鬼）

**Comment by wwl82** [comment]
不小心按到 unassign orz

**Comment by MontyPan** [comment]
> 不小心按到 unassign orz

那就自己 assign 回來啊老闆... 😑

**Comment by wwl82** [comment]
抱歉, 還不太會操作 github XD 剛剛用手機找不到 assign 的地方, 謝謝~

**Comment by MontyPan** [comment]
> #### 注意 ####
> 此 comment 需要讀過、但不需要回覆

------------------------------------------------

> 抱歉, 還不太會操作 github XD 剛剛用手機找不到 assign 的地方, 謝謝~

1. 沒有用全形標點符號
2. GitHub 大小寫有誤
3. 這聽起來很像靈異現象，至少我剛剛看手機版網頁（手機 app 版沒用過）：
    + 我找不到 unassign 字樣
    + 能 unassign 的地方就是「Assignees」點下去的 clear assignee，assign 人當然也是同樣地方

最後，我不建議用手機操作 GitHub（即使沒用過的 app 我也不樂觀），光是鍵盤推測 UI/UX 設計就覺得不太可能對新手友善。當然，理論上我不會知道你是用什麼方式操作 GitHub 的... 😑
